/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class AppearCount : TBase
{
  private string _feaid;
  private int _count;
  private string _channelid;

  public string Feaid
  {
    get
    {
      return _feaid;
    }
    set
    {
      __isset.feaid = true;
      this._feaid = value;
    }
  }

  public int Count
  {
    get
    {
      return _count;
    }
    set
    {
      __isset.count = true;
      this._count = value;
    }
  }

  public string Channelid
  {
    get
    {
      return _channelid;
    }
    set
    {
      __isset.channelid = true;
      this._channelid = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool feaid;
    public bool count;
    public bool channelid;
  }

  public AppearCount() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Feaid = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              Count = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              Channelid = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("AppearCount");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Feaid != null && __isset.feaid) {
        field.Name = "feaid";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Feaid);
        oprot.WriteFieldEnd();
      }
      if (__isset.count) {
        field.Name = "count";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Count);
        oprot.WriteFieldEnd();
      }
      if (Channelid != null && __isset.channelid) {
        field.Name = "channelid";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Channelid);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("AppearCount(");
    bool __first = true;
    if (Feaid != null && __isset.feaid) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Feaid: ");
      __sb.Append(Feaid);
    }
    if (__isset.count) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Count: ");
      __sb.Append(Count);
    }
    if (Channelid != null && __isset.channelid) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Channelid: ");
      __sb.Append(Channelid);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

