/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class SCountInfoAndCmpFaceLog : TBase
{
  private List<SCountInfo> _sCountInfo;
  private List<CmpFaceLog> _cmpFaceLog;

  public List<SCountInfo> SCountInfo
  {
    get
    {
      return _sCountInfo;
    }
    set
    {
      __isset.sCountInfo = true;
      this._sCountInfo = value;
    }
  }

  public List<CmpFaceLog> CmpFaceLog
  {
    get
    {
      return _cmpFaceLog;
    }
    set
    {
      __isset.cmpFaceLog = true;
      this._cmpFaceLog = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool sCountInfo;
    public bool cmpFaceLog;
  }

  public SCountInfoAndCmpFaceLog() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                SCountInfo = new List<SCountInfo>();
                TList _list12 = iprot.ReadListBegin();
                for( int _i13 = 0; _i13 < _list12.Count; ++_i13)
                {
                  SCountInfo _elem14;
                  _elem14 = new SCountInfo();
                  _elem14.Read(iprot);
                  SCountInfo.Add(_elem14);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                CmpFaceLog = new List<CmpFaceLog>();
                TList _list15 = iprot.ReadListBegin();
                for( int _i16 = 0; _i16 < _list15.Count; ++_i16)
                {
                  CmpFaceLog _elem17;
                  _elem17 = new CmpFaceLog();
                  _elem17.Read(iprot);
                  CmpFaceLog.Add(_elem17);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("SCountInfoAndCmpFaceLog");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (SCountInfo != null && __isset.sCountInfo) {
        field.Name = "sCountInfo";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, SCountInfo.Count));
          foreach (SCountInfo _iter18 in SCountInfo)
          {
            _iter18.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (CmpFaceLog != null && __isset.cmpFaceLog) {
        field.Name = "cmpFaceLog";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, CmpFaceLog.Count));
          foreach (CmpFaceLog _iter19 in CmpFaceLog)
          {
            _iter19.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("SCountInfoAndCmpFaceLog(");
    bool __first = true;
    if (SCountInfo != null && __isset.sCountInfo) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("SCountInfo: ");
      __sb.Append(SCountInfo);
    }
    if (CmpFaceLog != null && __isset.cmpFaceLog) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("CmpFaceLog: ");
      __sb.Append(CmpFaceLog);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

