/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class SuspectAnalysisInfo : TBase
{
  private RealtimeCapInfoLBS _capcfg;
  private List<SuspectAnalysis> _sulist;

  public RealtimeCapInfoLBS Capcfg
  {
    get
    {
      return _capcfg;
    }
    set
    {
      __isset.capcfg = true;
      this._capcfg = value;
    }
  }

  public List<SuspectAnalysis> Sulist
  {
    get
    {
      return _sulist;
    }
    set
    {
      __isset.sulist = true;
      this._sulist = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool capcfg;
    public bool sulist;
  }

  public SuspectAnalysisInfo() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Capcfg = new RealtimeCapInfoLBS();
              Capcfg.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                Sulist = new List<SuspectAnalysis>();
                TList _list40 = iprot.ReadListBegin();
                for( int _i41 = 0; _i41 < _list40.Count; ++_i41)
                {
                  SuspectAnalysis _elem42;
                  _elem42 = new SuspectAnalysis();
                  _elem42.Read(iprot);
                  Sulist.Add(_elem42);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("SuspectAnalysisInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Capcfg != null && __isset.capcfg) {
        field.Name = "capcfg";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        Capcfg.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Sulist != null && __isset.sulist) {
        field.Name = "sulist";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Sulist.Count));
          foreach (SuspectAnalysis _iter43 in Sulist)
          {
            _iter43.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("SuspectAnalysisInfo(");
    bool __first = true;
    if (Capcfg != null && __isset.capcfg) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Capcfg: ");
      __sb.Append(Capcfg== null ? "<null>" : Capcfg.ToString());
    }
    if (Sulist != null && __isset.sulist) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Sulist: ");
      __sb.Append(Sulist);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

